name: Track Issue Start Time
on:
  issues:
    types: [labeled]  # Triggers when a label is added

jobs:
  start_timer:
    if: github.event.label.name == 'In Progress'
    runs-on: ubuntu-latest
    steps:
      - name: Set Start Time
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
          -d '{"labels": ["In Progress"], "body": "Started At: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"}'

